package com.darius.unison.playback

import java.util.ArrayDeque

/**
 * Tracks player intent changes initiated by Unison itself.
 *
 * Media3 callbacks may also be generated by audio focus, noisy-route policy, platform policy, or
 * another system component. The adapter consumes an expected entry for app-owned mutations; an
 * unmatched callback is therefore external and must never be "repaired" into audible playback.
 */
class ExpectedPlayerIntentTracker(
    private val ttlNs: Long = DEFAULT_TTL_NS,
    private val maxPending: Int = DEFAULT_MAX_PENDING,
) {
    private data class Change(
        val value: Boolean,
        val source: String,
        val expiresAtNs: Long,
    )

    private val pending = ArrayDeque<Change>()

    fun expect(value: Boolean, source: String, nowNs: Long) {
        discardExpired(nowNs)
        pending.addLast(Change(value, source, nowNs + ttlNs))
        while (pending.size > maxPending) pending.removeFirst()
    }

    fun consume(value: Boolean, nowNs: Long): String? {
        discardExpired(nowNs)
        val first = pending.peekFirst() ?: return null
        if (first.value != value) return null
        pending.removeFirst()
        return first.source
    }

    fun clear() = pending.clear()

    private fun discardExpired(nowNs: Long) {
        while (pending.peekFirst()?.expiresAtNs?.let { it < nowNs } == true) {
            pending.removeFirst()
        }
    }

    companion object {
        const val DEFAULT_TTL_NS = 2_000_000_000L
        const val DEFAULT_MAX_PENDING = 8
    }
}
