#!/usr/bin/env python3
"""Generate the Dashboard Permission literal contract from the server catalogue."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SERVER = ROOT / "server"
OUTPUT = ROOT / "dashboard" / "src" / "generated" / "permissions.ts"


def _typescript_name(code: str) -> str:
    words = re.split(r"[^a-zA-Z0-9]+", code)
    return words[0] + "".join(word[:1].upper() + word[1:] for word in words[1:])


def _render() -> str:
    sys.path.insert(0, str(SERVER))
    from app.application.iam.catalogue import PERMISSION_DEFINITIONS

    codes = [definition.code.value for definition in PERMISSION_DEFINITIONS]
    entries = "\n".join(
        f'  {_typescript_name(code)}: "{code}",' for code in codes
    )
    values = "\n".join(f'  "{code}",' for code in codes)
    return f"""// Generated by scripts/generate-permission-contract.py. Do not edit.

export const PERMISSIONS = {{
{entries}
}} as const;

export const PERMISSION_CODES = [
{values}
] as const;

export type PermissionCode = (typeof PERMISSION_CODES)[number];
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = _render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != rendered:
            print(f"Permission contract drift: regenerate {OUTPUT.relative_to(ROOT)}")
            return 1
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
